trigger:
  branches:
    include:
      - main

stages:
  - stage: Terraform_Deploy
    jobs:
      - job: Apply_Terraform
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'

          - checkout: self

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'MyServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az account set --subscription "<subscription-id>"
                cd terraform
                terraform init -backend-config="storage_account_name=terraformstate123"
                terraform plan -var-file="dev.tfvars"
                terraform apply -auto-approve -var-file="dev.tfvars"